Add : User models.py 추가
wecode-bootcamp-korea/12-Naweki-backend pull request #1
Opened 2020-09-17 04:50 UTC by FineLineFE

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- user model 앱 생성 및 models.py 작성
		 
## 수정 사항들 자세한 내용
- user app 생성

## 기타 질문 및 특이 사항
- user models.py 작성

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ v ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ v ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ v ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-17 07:26 UTC, lordmyshepherd requested changes

2020-09-17 07:26 UTC, lordmyshepherd commented on users/models.py
> +    password     = models.CharField(max_length = 400)
password는 400자면 충분한가요?

2020-09-17 10:54 UTC, FineLineFE commented on users/models.py
> +
수정해서 올렸습니다!

2020-09-17 10:54 UTC, FineLineFE commented on users/models.py
> +    password     = models.CharField(max_length = 400)
600자로 수정해서 올렸습니다!

2020-09-18 05:01 UTC, FineLineFE commented on users/models.py
> +    password     = models.CharField(max_length = 400)
멘토님 어제 수정했는데 혹시 또 반영해야할 사항이 있는건가요?!

2020-09-18 08:23 UTC, lordmyshepherd approved these changes

2020-09-18 08:24 UTC, lordmyshepherd commented
LGTM 👍

2020-09-18 08:24 UTC, merged