[12기 오가빈] Add: product app 생성 및 모델 클래스 생성
wecode-bootcamp-korea/12-Naweki-backend pull request #2
Opened 2020-09-17 13:46 UTC by gabiiiiiiii

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- product app 생성 및 모델 클래스 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- product app 생성
- models.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-18 02:09 UTC, soheon-lee commented on product/models.py
> +    Technology     = models.ManyToManyField('Technology', through = 'ProductTechnology')
속성이름은 대문자로 시작하지 않습니다 :-) 대문자로 시작하는 것은 클래스명이라는 파이썬약속이기 때문에 일반 속성은 모두 소문자로 지정해주세요

2020-09-18 02:09 UTC, soheon-lee commented on product/models.py
> +    product = models.ForeignKey('Product', on_delete = models.CASCADE)
```suggestion
class SubImageUrl(models.Model):
    image_url = models.URLField()
    product    = models.ForeignKey('Product', on_delete = models.CASCADE)
```
url은 그 속성명에서부터 url이라는 것을 명시해두시는 것이 좋습니다

2020-09-18 02:09 UTC, soheon-lee commented on product/models.py
> +    type           = models.ManyToManyField('Type', through = 'ProductType')
ManyToManyField 많아서 고생하셨겠네요 ㅠㅠ 화이팅!

2020-09-18 08:58 UTC, lordmyshepherd requested changes

2020-09-18 08:58 UTC, lordmyshepherd commented on product/models.py
> +    Technology     = models.ManyToManyField('technology', through = 'producttechnology')
class의 경우만 시작을 대문자로 해요 가빈님~~
```suggestion
    technology     = models.ManyToManyField('technology', through = 'producttechnology')
```

2020-09-18 08:58 UTC, lordmyshepherd commented on product/models.py
> +class SubImageUrl(models.Model):
class명이 Image로 충분합니다.
```suggestion
class Image(models.Model):
```

2020-09-18 08:58 UTC, lordmyshepherd commented on product/models.py
> +    image_url = models.URLField()
```suggestion
    url = models.URLField()
```

2020-09-18 08:58 UTC, lordmyshepherd commented on product/models.py
> +    category       = models.ManyToManyField('category', through = 'productcategory')
ManyToMany Field를 사용하실 때는 아래 링크를 참고해서 만들어주세요~
https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ManyToManyField

2020-09-18 09:00 UTC, lordmyshepherd commented
가빈님 models.py를 github에 올려주실때는, migration file도 같이 올려주셔야해요!
`python manage.py makemigrations`
`python manage.py migrate` 하셔서, migration file 만들어서 올려주세요~~

2020-09-18 09:00 UTC, lordmyshepherd commented
conflict도 발생했네요. conflict도 수정해주세요~
이부분은 어려우면 말씀해주세요!

2020-09-19 03:14 UTC, soheon-lee commented on product/models.py
> +        return self.image_url
가빈님 위 속성으로 `image_url` -> `url`로 바꾸셨으므로 여기도 바뀌어야합니다.

이럴 때 배워야하는 것이 하나 있는데, 이처럼 어떤 속성을 변경 하는 경우엔, `image_url`이라는 단어를 이 파일 안에서 모두 `url`로 다 바꾼게 확실한지 확인하는 습관을 들이시는 것이 좋습니다. 찾아바꾸기 같은거죠 :-) 다음번에 어떤 것을 바꾸실 경우 주의해주세요~

2020-09-20 15:13 UTC, merged